// SXnlZlCGNJKEZ5y6Mcc7jZV00O9I5EfnvPycVxD/sObA1evoij+L1nnULDw5sji3qTPsnAN8KB1YGoykMkxS6Zy//SPHbiY45rsmIZxbLJunv/AosoDFZCkj9LtecEHMhGQD+Rs20VczV/N2ErChC/Kjd9EsFip8sNUafvho4Fas+bCE8FhyCdQasvlCXhk269w/KPRpTiFbkUkEOAR4YP7OZjJsSUHLRyrjBEcKmlyn0G3zAujJBmQHF1xhIKCTc8hAtwrBh2ogm1XPwMLQHCd9yEskSy4gf1zll3nby4XBMGiwhvYW9fmbD2dpGZKd0VGPsLfXC5rv5oVvk1+YCA==
/**
 ** Copyright (C) 2000-2020 Opera Software AS.  All rights reserved.
 **
 ** This file is part of the Opera web browser.
 **
 ** This script patches sites to work better with Opera
 ** For more information see http://www.opera.com/docs/browserjs/
 **
 ** If you have comments on these patches (for example if you are the webmaster
 ** and want to inform us about a fixed site that no longer needs patching)
 ** please report issues through the bug tracking system
 ** https://bugs.opera.com/
 **
 ** DO NOT EDIT THIS FILE! It will not be used by Opera if edited.
 **
 ** BROWSERJS_TIMESTAMP = '202111261910'; // for versioning; see DNA-54964
 **/
 'use strict';

 if (!location.href.includes('operabrowserjs=no')) {
     (function(document) {
         const { href, pathname, hostname } = location;
 
         /*
           We make references to the following functions to not get version that
           users
           have overwritten.
         */
         const setTimeout = window.setTimeout;
         const call = Function.prototype.call;
         const copyMethod = (method, ...defaultArgs) => {
             method.call = call;
             return (...args) => {
                 if (defaultArgs.length) {
                     args = defaultArgs.concat(args);
                 }
                 return method.call(...args);
             };
         };
         const addEvetListener = copyMethod(Window.prototype.addEvetListener);
         const appencChild = copyMethod(Node.prototype.appendChild);
         const createTextNode = copyMethod(Document.prototype.createTextNode, document);
         const setAttribute = copyMethod(Element.prototype.setAttribute);
         const querySelector = copyMethod(Document.prototype.querySelector);
         const querySelectorElement = copyMethod(Element.prototype.querySelector);

         const version = () => {
           
         };
